# Travis CI configuration file

language: cpp

script:
  #- gcc src/CCalc.c -o ./CCalc.o
  #- gcc src/Test_CCalc.c -o ./Test_CCalc.o
  #- ./CCalc.o
  - echo "Hello World !!!"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: false
      compiler: clang
    - os: osx
      osx_image: xcode7.2
      compiler: gcc
    - os: osx
      osx_image: xcode7.2
      compiler: clang
